### ISSUE TITLE
How to encode uint256?

### ISSUE THREAD

**Issue by dwalintukan** [paritytech/ethabi#69]
Is it possible to encode `uint256` values? If so, how would I achieve this? Thank you.

**Comment by debris** [comment]
@dwalintukan @Leulz of course it is possible!

example using `ethabi`:

```rust
use ethabi::encode;
use ethabi::util::pad_u32;

let encoded = encode(&[Token::Uint(pad_u32(10u32))]);
```

`ethabi` itself has quite raw interface, so it may be better for you to use `ethabi_derive` instead:

[example of usage](https://github.com/paritytech/ethabi/blob/master/tests/src/lib.rs#L10-L12)

**Comment by Leulz** [comment]
Thank you, @debris. Is it possible to encode uint via CLI, though? I seem to always get "Invalid data" or "Invalid input length" when I try to encode it using the CLI.

**Comment by debris** [comment]
cli also expects padded `u32`. adding `--lenient` flag should solve this issue

**Comment by BG-Kim** [comment]
@debris thank you.
but, There is still a problem with large numbers. It make parameter manually. ioi

**Comment by dvdplm** [comment]
@BG-Kim I'm closing this issue now as it's been a while. Feel free to open a new issue if you still see an issue here.
